name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - "README.md"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          make setup
          make install

      - name: Check the CLI
        run: |
          source ~/.bashrc
          
          if ! command -v cmmd-pytorch >/dev/null 2>&1; then
            echo "Error: The command 'cmmd-pytorch' is not available." >&2
            exit 1
          fi
      
          echo "The command 'cmmd-pytorch' is available."

      - name: Format
        run: |
          make format

      - name: Lint
        run: |
          make lint

      - name: Type check
        run: |
          make typecheck

      - name: Run tests
        run: |
          make test
